### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by ZZZWWL** [MingshiYan/BIPN#2]
作者您好，我在浮现你的代码时发现tmall和淘宝数据集上的实验结果与论文上的相差挺大的，我是按照日志文件里的最佳参数跑的，这是什么原因没搞清楚，希望您能够赐教，以下是我在这两个数据集上跑的最好的效果。
[tmall_enb_64_2024-10-26 08_09_05.log](https://github.com/user-attachments/files/17647439/tmall_enb_64_2024-10-26.08_09_05.log)
[taobao_enb_64_2024-10-21 10_23_18.log](https://github.com/user-attachments/files/17647440/taobao_enb_64_2024-10-21.10_23_18.log)

**Comment by MingshiYan** [comment]
你好，更新一下代码，再grid search一下试试。有可能是初始化的问题。
